##
## AimHarder Booking Bot
## Author: Helena Ribera <heleribera@gmail.com>
## Website: www.hriberaponsa.com
##
users:
  helena:
    credentials:
      email: "EMAIL_HELENA"
      password: "PASSWORD_HELENA"
    classes:
      hyrox:
        id: 25375
        sessions:
          - time: "17:00 - 18:00"
            days_ahead: [1, 3]
          - time: "18:00 - 19:00"
            days_ahead: [4]
      strength_&_conditioning:
        id: 27780
        sessions:
          - time: "17:00 - 18:00"
            days_ahead: [4]
  laura:
    credentials:
      email: "EMAIL_LAURA"
      password: "PASSWORD_LAURA"
    classes:
      hyrox:
        id: 25375
        sessions:
          - time: "17:00 - 18:00"
            days_ahead: [1]
          - time: "18:00 - 19:00"
            days_ahead: [2, 4]
      strength_&_conditioning:
        id: 27780
        sessions:
          - time: "17:00 - 18:00"
            days_ahead: [2]
          - time: "19:00 - 20:00"
            days_ahead: [4]
      wod:
        id: 24743
        sessions:
          - time: "16:00 - 17:00"
            days_ahead: [1]
