users:
  helena:
    credentials:
      email: "EMAIL_HELENA"
      password: "PASSWORD_HELENA"
    classes:
      hyrox:
        id: 25375
        sessions:
          - time: "17:00 - 18:00"
            days_ahead: [1, 3]
          - time: "18:00 - 19:00"
            days_ahead: [4]

      strength_conditioning:
        id: 27780
        sessions:
          - time: "17:00 - 18:00"
            days_ahead: [4]
